# Default Macchina theme.
# See: https://github.com/Macchina-CLI/macchina/blob/main/contrib/themes/Hydrogen.toml

prefer_small_ascii = true
separator = ""
key_color = "Green"

[custom_ascii]
path = "~/.config/macchina/crt.ascii"
