# Default Macchina theme.
# See: https://github.com/Macchina-CLI/macchina/blob/main/theme/Carbon.toml

padding = 0
separator = ""
key_color = "Green"
palette = "Dark"

[custom_ascii]
path = "~/.config/macchina/ascii_saturn"

[box]
title = ""
visible = true

[box.inner_margin]
x = 3
y = 1
