# Configures Macchina.
# See: https://github.com/Macchina-CLI/macchina/blob/main/macchina.toml

theme = "Default"
custom_ascii = "~/.config/macchina/ascii_saturn"
show = [
    "Host",
    "Machine",
    "Kernel",
    "Distribution",
    "OperatingSystem",
    "DesktopEnvironment",
    "WindowManager",
    "Resolution",
    "Backlight",
    "Packages",
    "LocalIP",
    "Terminal",
    "Shell",
    "Uptime",
]
interface = "eth0"
palette = "Dark"
