# Configures Macchina.
# See: https://github.com/Macchina-CLI/macchina/blob/main/macchina.toml

custom_ascii = "~/.config/macchina/ascii_dino"
no_box = true
no_separator = true
hide = ["Processor", "ProcessorLoad", "Memory", "Battery"]
color = "Green"
interface = "eth0"
palette = "Full"
