# See: https://starship.rs/config/

[character]
error_symbol = "[❯](bold green)"
success_symbol = "[❯](bold green)"
vimcmd_symbol = "[❯](bold blue)"
vimcmd_replace_one_symbol = "[❯](bold red)"
vimcmd_replace_symbol = "[❯](bold red)"
vimcmd_visual_symbol = "[❯](bold purple)"

[directory]
format = "[($read_only )$path/]($style) "
read_only = ""

[docker_context]
symbol = "󰡨 "

[git_branch]
truncation_length = 24

[git_status]
ahead = "↑${count}"
behind = "↓${count}"
diverged = "${ahead_count}↑${behind_count}↓"

[golang]
symbol = " "

[hostname]
style = "bold green"

[kubernetes]
disabled = false
symbol = "󱃾 "
style = "bold blue"

[lua]
symbol = " "

[package]
disabled = true
symbol = " "
style = "bold yellow"

[rust]
symbol = " "

[status]
disabled = false
format = "[\\[$status\\]]($style) "
