# See: https://starship.rs/config/

[character]
error_symbol = "[λ](bold green)"
success_symbol = "[λ](bold green)"
vimcmd_symbol = "[λ](bold blue)"
vimcmd_replace_one_symbol = "[λ](bold red)"
vimcmd_replace_symbol = "[λ](bold red)"
vimcmd_visual_symbol = "[λ](bold purple)"

[directory]
format = "[($read_only )$path/]($style) "
read_only = ""

[git_branch]
truncation_length = 24

[git_status]
ahead = "↑${count}"
behind = "↓${count}"
diverged = "${ahead_count}↑${behind_count}↓"

[golang]
symbol = " "

[kubernetes]
disabled = false
symbol = "󱃾 "
style = "bold blue"
detect_env_vars = ["REMOVE_ME_WHEN_#5978_GETS_FIXED"]
detect_folders = ["kubernetes", "kube", "k8s", "kustomize"]
detect_files = ["Tiltfile"]
contexts = [{ context_pattern = "docker-desktop", context_alias = "local" }]

[lua]
symbol = " "

[package]
disabled = true

[rust]
symbol = " "

[status]
disabled = false
format = "[\\[$status\\]]($style) "
