# Configures Starship.
# See: https://starship.rs/config/

format = "$time$all"

[git_status]
ahead = "${count}↑"
behind = "${count}↓"
diverged = "${ahead_count}↑${behind_count}↓"

[hostname]
style = "bold green"

[nodejs]
symbol = "⬢ "

[status]
disabled = false
format = "[$status]($style) "

[time]
disabled = false
format = "[$time]($style) "
time_format = "%R"
style = "bold black"
