# See: https://starship.rs/config/

format = "[╭](bold black) $all$fill$time$line_break[╰](bold black) $jobs$status$shell$character"

[character]
error_symbol = "[I ❯](bold green)"
success_symbol = "[I ❯](bold green)"
vimcmd_symbol = "[N ❯](bold blue)"
vimcmd_replace_one_symbol = "[R ❯](bold red)"
vimcmd_replace_symbol = "[R ❯](bold red)"
vimcmd_visual_symbol = "[V ❯](bold purple)"

[directory]
format = "[($read_only )$path/]($style) "
read_only = ""

[fill]
symbol = "─"
style = "bright-black"

[git_branch]
truncation_length = 24

[git_status]
ahead = "↑${count}"
behind = "↓${count}"
diverged = "${ahead_count}↑${behind_count}↓"

[golang]
symbol = " "

[hostname]
style = "bold green"

[lua]
symbol = " "

[package]
disabled = true
symbol = " "
style = "bold yellow"

[rust]
symbol = " "

[status]
disabled = false
format = "[\\[$status\\]]($style) "

[time]
disabled = false
format = "[](bright-black)[ ](bg:bright-black)[$time](inverted bright-black)[ ](bg:bright-black)[](bright-black)"
time_format = "%R"
