# Configures Starship.
# See: https://starship.rs/config/

format="$time$all"

[docker_context]
disabled = false

[hostname]
style = "bold green"

[nodejs]
symbol = "⬢ "

[python]
python_binary = "python3"

[time]
disabled = false
format = "[$time]($style) "
time_format = "%R"
style = "bold black"
