# Configures Starship.
# See: https://starship.rs/config/

format = "$time$all"

[character]
error_symbol = "[I ❯](bold green)"
success_symbol = "[I ❯](bold green)"
vimcmd_symbol = "[N ❯](bold cyan)"
vimcmd_replace_one_symbol = "[R ❯](bold red)"
vimcmd_replace_symbol = "[R ❯](bold red)"
vimcmd_visual_symbol = "[V ❯](bold purple)"

[git_status]
ahead = "${count}↑"
behind = "${count}↓"
diverged = "${ahead_count}↑${behind_count}↓"

[hostname]
style = "bold green"

[nodejs]
symbol = "⬢ "

[status]
disabled = false
format = "[\\[$status\\]]($style) "

[time]
disabled = false
format = "[$time]($style) "
time_format = "%R"
style = "bold black"
