session_selector:
  width: 64
  height: 24
  scrolloff: 4
  inverted: false
  results:
    style: null
    border: plain
    border_style: fg:#BDAEC3
    title: " Results "
    title_style: null
    item_style: null
    item_match_style: fg:blue
    selection_style: bg:#433737 bold
    selection_prefix: "❯ "
    selection_prefix_style: fg:#DAA992
  prompt:
    style: null
    border: plain
    border_style: fg:#BDAEC3
    title: " Sessions "
    title_style: null
    pattern_style: null
    pattern_prefix: "   "
    pattern_prefix_style: null
keybinds:
  session_selector: [C-s, M-s]
  last_session: [w]
