#!/usr/bin/env bash

branch=$(git branch --show-current 2>/dev/null)

if [ ${branch} != "main" ] && [ ${branch} != "master" ]; then
    exit 0
fi

read -n 1 -r -p "Are you sure you want to push to '${branch}'? [y/N] " < /dev/tty
if [ "${REPLY}" != "" ]; then
    echo
fi
if [ "${REPLY}" = "y" ] || [ "${REPLY}" = "Y" ]; then
    exit 0
fi

exit 1
