#!/bin/bash

GITCONFIG_PROFILE_FILE_NAME=".gitconfig.profile"

while test ! -f "${PWD}/${GITCONFIG_PROFILE_FILE_NAME}" -a "${PWD}" != "/"; do
    PWD=$(dirname "${PWD}")
done

if test "${PWD}" == "/"; then
    echo "error: No \`${GITCONFIG_PROFILE_FILE_NAME}\` file in parent directories found."
    exit 1
fi

include_path_current=$(git config --local --default="" include.path)
include_path_new="${PWD}/${GITCONFIG_PROFILE_FILE_NAME}"
if test "${include_path_current}" != "${include_path_new}"; then
    git config --local include.path "${include_path_new}"
    echo "\`include.path\` has been set to \`${include_path_new}\`. Please commit again."
    exit 1
fi

user_email=$(git config --local --includes --default="" user.email)
if test "${user_email}" == ""; then
    echo "error: \`user.email\` not set."
    exit 1
fi

user_signing_key=$(git config --local --includes --default="" user.signingkey)
if test "${user_signing_key}" == ""; then
    echo "error: \`user.signingkey\` not set."
    exit 1
fi

user_name=$(git config user.name)
echo "Committing as ${user_name} <${user_email}>…"
