# Disables user inputs and traps exits to enable them again.
trap 'stty echo' EXIT
stty -echo

# Loads the welcome message.
source ~/.zsh_welcome

# Loads key-bindings.
source ~/.zsh_key-bindings

# Loads aliases.
source ~/.zsh_aliases

# Loads plugins if they exist.
[ -f ~/.zsh_plugins ] && source ~/.zsh_plugins

# Initializes Starship.
# See: https://starship.rs/
source <(starship init zsh)
