# Disables user inputs and traps exits to enable them again.
trap 'stty echo' EXIT
stty -echo

# Loads the welcome message.
source ~/.zsh_welcome

# Loads key-bindings.
source ~/.zsh_key-bindings

# Loads aliases.
source ~/.zsh_aliases

# Loads plugins if they exist.
[ -f ~/.zsh_plugins ] && source ~/.zsh_plugins

# Extends PATH with the user's .local/bin directory if it exists.
[ -d ~/.local/bin ] && export PATH=~/.local/bin:$PATH

# Sets the window title to the current user and working directory.
set_window_title() {
  echo -ne "\033]0; $([ $(id -u) = 0 ] && printf "${USER} in ")${"${PWD}"/"${HOME}"/"~"} \007"
}

# Adds new functions to be executed before the prompt.
precmd_functions+=(set_window_title)

# Initializes Starship.
# See: https://starship.rs/
source <(starship init zsh)
