# Disables user inputs and traps exits to enable them again.
trap 'stty echo 2>/dev/null' EXIT
stty -echo 2>/dev/null

# Loads the welcome message.
source ~/.zsh_welcome

# Loads key-bindings.
source ~/.zsh_key-bindings

# Loads aliases.
source ~/.zsh_aliases

# Loads plugins if they exist.
[ -f ~/.zsh_plugins ] && source ~/.zsh_plugins

# Adds directories to the PATH variable.
path+=(
  ~/.local/bin
)

# Sets the window title to the current user, host and working directory.
set_window_title() {
  echo -ne "\033]0;$([ $(id -u) = 0 ] || [ "$USER" != "$LOGNAME" ] || [ "$SSH_CONNECTION" ] && printf "${USER} in ")$([ "$SSH_CONNECTION" ] && printf "${HOST} in ")${"${PWD}"/"${HOME}"/"~"}\007"
}

# Adds functions that are executed before the prompt.
precmd_functions+=(
  set_window_title
)

# Initializes Starship.
# See: https://starship.rs/
source <(starship init zsh)
